# Generated by Django 4.1 on 2022-08-31 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='review_title',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
